#
# SPDX-FileCopyrightText: 2026 John Samuel <johnsamuelwrites@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

"""Core 1.0 UI lowering pass.

Transforms reactive IR nodes into JavaScript/HTML output:

  IRObserveBinding  → reactive JS variable + Signal.set() call
  IROnChange        → addEventListener / signal.on_change() wiring
  IRCanvasBlock     → HTML element tree + reactive slot bindings
  IRRenderExpr      → DOM insertion call
  IRViewBinding     → stream_to_view() glue code

This module is intentionally backend-independent: the output is a
``UILoweringResult`` value object, not a file.  The calling codegen
orchestrator writes it to disk.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from multilingualprogramming.core.ir_nodes import (
    IRCanvasBlock,
    IRIdentifier,
    IRLiteral,
    IRNode,
    IRObserveBinding,
    IROnChange,
    IRProgram,
    IRRenderExpr,
    IRViewBinding,
)


# ---------------------------------------------------------------------------
# Result value object
# ---------------------------------------------------------------------------

@dataclass
class UILoweringResult:
    """Output of the UI lowering pass.

    js_preamble:   module-level JS (imports, reactive engine setup).
    js_signals:    Signal declarations (one per ``observe var``).
    js_handlers:   on_change handler registrations.
    js_canvas:     canvas block HTML/JS.
    js_bindings:   stream-to-view wiring JS.
    html_elements: list of HTML fragment strings (from canvas blocks).
    diagnostics:   list of warning / error strings.
    """

    js_preamble: str = ""
    js_signals: list[str] = field(default_factory=list)
    js_handlers: list[str] = field(default_factory=list)
    js_canvas: list[str] = field(default_factory=list)
    js_bindings: list[str] = field(default_factory=list)
    html_elements: list[str] = field(default_factory=list)
    diagnostics: list[str] = field(default_factory=list)

    def emit_js(self) -> str:
        """Return a single JS source string from all accumulated fragments."""
        parts = []
        if self.js_preamble:
            parts.append(self.js_preamble)
        parts.extend(self.js_signals)
        parts.extend(self.js_handlers)
        parts.extend(self.js_canvas)
        parts.extend(self.js_bindings)
        return "\n".join(parts)

    def emit_html(self) -> str:
        """Return a single HTML fragment string."""
        return "\n".join(self.html_elements)


# ---------------------------------------------------------------------------
# Lowering pass
# ---------------------------------------------------------------------------

class UILoweringPass:
    """Walk an IRProgram and emit reactive JS/HTML fragments."""

    def __init__(self) -> None:
        self._result = UILoweringResult()
        self._result.js_preamble = (
            "// Generated by Multilingual 1.0 UI lowering pass\n"
            "import { ReactiveEngine } from './multilingual_runtime.js';\n"
            "const _engine = new ReactiveEngine();"
        )

    def lower(self, program: IRProgram) -> UILoweringResult:
        """Lower *program* and return the accumulated result."""
        for node in program.body:
            self._lower_node(node)
        return self._result

    # ------------------------------------------------------------------
    # Node dispatch
    # ------------------------------------------------------------------

    def _lower_node(self, node: IRNode) -> None:
        if isinstance(node, IRObserveBinding):
            self._lower_observe(node)
        elif isinstance(node, IROnChange):
            self._lower_on_change(node)
        elif isinstance(node, IRCanvasBlock):
            self._lower_canvas(node)
        elif isinstance(node, IRRenderExpr):
            self._lower_render(node)
        elif isinstance(node, IRViewBinding):
            self._lower_view_binding(node)

    # ------------------------------------------------------------------
    # Individual lowering methods
    # ------------------------------------------------------------------

    def _lower_observe(self, node: IRObserveBinding) -> None:
        """Emit a reactive signal declaration."""
        initial = self._expr_to_js(node.value)
        js = (
            f"const {node.name} = _engine.declare({node.name!r}, {initial});"
        )
        self._result.js_signals.append(js)

    def _lower_on_change(self, node: IROnChange) -> None:
        """Emit a signal.on_change() handler."""
        signal_name = self._expr_to_js(node.signal)
        # Body lowering: just emit a comment placeholder for now
        body_js = "  /* handler body */"
        js = (
            f"_engine.get({signal_name}).on_change((newValue) => {{\n"
            f"{body_js}\n"
            f"}});"
        )
        self._result.js_handlers.append(js)

    def _lower_canvas(self, node: IRCanvasBlock) -> None:
        """Emit an HTML canvas element and JS slot wiring."""
        canvas_id = node.name or f"canvas_{id(node)}"
        html = f'<div id="{canvas_id}" class="ml-canvas"></div>'
        self._result.html_elements.append(html)

        # Recurse into children
        for child in node.children:
            if isinstance(child, IRObserveBinding):
                # slot binding
                js = (
                    f"_engine.get({child.name!r}).on_change((v) => {{\n"
                    f"  document.getElementById({canvas_id!r}).textContent = v;\n"
                    f"}});"
                )
                self._result.js_canvas.append(js)
            elif isinstance(child, IRNode):
                self._lower_node(child)

    def _lower_render(self, node: IRRenderExpr) -> None:
        """Emit a DOM insertion expression."""
        target_js = self._expr_to_js(node.target)
        value_js = self._expr_to_js(node.value)
        js = (
            f"(function() {{\n"
            f"  const _el = document.getElementById({target_js});\n"
            f"  if (_el) _el.textContent = {value_js};\n"
            f"}})();"
        )
        self._result.js_canvas.append(js)

    def _lower_view_binding(self, node: IRViewBinding) -> None:
        """Emit stream-to-view wiring."""
        signal_js = self._expr_to_js(node.signal)
        target_js = self._expr_to_js(node.target)
        js = (
            f"streamToView({signal_js}, {target_js}, {{ append: true }});"
        )
        self._result.js_bindings.append(js)

    # ------------------------------------------------------------------
    # Expression helpers
    # ------------------------------------------------------------------

    def _expr_to_js(self, node: IRNode | None) -> str:
        """Minimal expression lowering to a JS string fragment."""
        if node is None:
            return "null"
        if isinstance(node, IRLiteral):
            if node.kind == "string":
                return repr(str(node.value))
            return str(node.value)
        if isinstance(node, IRIdentifier):
            return node.name
        # Fallback: emit a comment with the class name
        return f"/* {type(node).__name__} */"


# ---------------------------------------------------------------------------
# Convenience entry point
# ---------------------------------------------------------------------------

def lower_to_ui(program: IRProgram) -> UILoweringResult:
    """Lower *program* to reactive UI output and return the result."""
    return UILoweringPass().lower(program)
